Layer iconography
developmentseed/aep pull request #46
Opened 2021-04-05 15:25 UTC by ricardoduplos

2021-04-05 15:54 UTC, olafveerman commented
This looks great.

@ricardoduplos One thing I noticed: Mean Wind Speed is the last layer in the panel. On my screen it sits on the bottom of the visible area. When I click the info icon, nothing seems to happen, while in reality the info drawer opens outside of the visible area. My first thought was that no additional information was available.

## Docs
I will add documentation to this PR, so let's hold off of merging for now.

2021-04-05 16:46 UTC, ricardoduplos commented
@olafveerman Thanks for the feedback. I'm aware of the drawer visibility problem. I'm discussing possible solutions with @danielfdsilva.

2021-04-06 12:14 UTC, olafveerman commented
The latest commits add:

* documentation for legends
* basic validation for the legend definition 

Both need feedback from @danielfdsilva for accuracy and completeness.

## :bug: 
@danielfdsilva I noticed a bug, when `dashed` is not specified on a `line` layer, the app breaks:

```
There was an error in your GraphQL query:
Cannot query field "dashed" on type "LayerLegend".
```

2021-04-06 14:19 UTC, danielfdsilva requested changes

2021-04-06 14:19 UTC, danielfdsilva commented on gatsby-node.js
> +        icon: String
```suggestion
        icon: String
        dashed: Boolean
```

2021-04-06 14:22 UTC, olafveerman approved these changes

2021-04-06 14:24 UTC, merged